# Pytorch Basics

In [1]:
import torch

In [2]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7548, 0.8663, 0.3409],
        [0.6914, 0.4682, 0.9232],
        [0.5952, 0.8078, 0.6277],
        [0.2828, 0.1086, 0.8140],
        [0.1439, 0.2176, 0.5879]])


In [3]:
x = torch.empty(2, 2, 3)
print(x)

tensor([[[0.0000e+00, 1.5846e+29, 0.0000e+00],
         [1.5846e+29, 9.8091e-45, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 3.5733e-43],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [4]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [5]:
x = torch.zeros(2, 2, dtype=torch.int)
print(x)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)


In [6]:
print(x.size())

torch.Size([2, 2])
